import type { Metadata } from 'next'
import { Inter, Annapurna_SIL } from 'next/font/google'
import { cn } from '@/lib/utils'
import { ScrollTopButton } from '@/components/scroll-top'

import Link from 'next/link'

import './globals.css'

export const metadata: Metadata = {
  title: 'Rivasyst',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const annapurna_sil = Annapurna_SIL({
  weight: ['400', '700'],
  subsets: ['latin', 'devanagari', 'latin-ext'],
  variable: '--font-annapurna-sil',
  display: 'swap',
})

interface Props {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Props>) {
  function getYear() {
    return new Date().getFullYear()
  }

  return (
    <html lang='en'>
      <body
        className={cn(
          annapurna_sil.variable,
          inter.variable,
          'relative antialiased after:w-full after:h-full after:bg-stone-500 after:left-0 after:top-0 after:absolute after:z-[-50] after:mix-blend-multiply'
        )}
        style={{
          backgroundImage: 'url(/axiom.png)',
          backgroundSize: '50px',
        }}
      >
        <div className='w-full min-h-dvh text-stone-50'>
          <div className='w-full max-w-screen-8xl mx-auto'>
            <header className='w-full h-20 flex items-center justify-between p-6 lg:px-16 xl:px-24'>
              <Link
                href='/'
                className='font-bold text-lg xl:text-2xl tracking-tighter hover:opacity-50 transition-all'
              >
                rivasyst
              </Link>

              <Link
                href='/auth/login'
                className='tracking-tighter hover:opacity-50 transition-all'
              >
                Login
              </Link>
            </header>
            {children}
            <footer className='w-full h-20 mt-96 p-6 lg:px-16 xl:px-24 flex items-center justify-between border-t border-t-stone-400 text-stone-50'>
              <p className='text-sm'>
                © {getYear()} Rivasyst. All rights reserved.
              </p>
              <ScrollTopButton />
            </footer>
          </div>
        </div>
      </body>
    </html>
  )
}
