import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'

import './globals.css'

export const metadata: Metadata = {
  title: 'Rivasyst',
  description: 'Generated by create next app',
}

const inter = Inter()

interface Props {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang='en'>
      <body className={cn('antialiased', inter.className)}>{children}</body>
    </html>
  )
}
